config/routes.rb
Rails.application.routes.draw do
  root to: 'groups#index'
  devise_for :users
  resources :users, only: [:index,:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do 
      resources :messages, only: :index, defaults: { format: 'json' } 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
  has_many :messages

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user).where("id > ?", params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  # def edit
  # end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group 

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group) }
        format.json
      end
    else
      @message = @group.message.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
    Time.zone ='Tokyo'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?) and id != ?', "%#{params[:keyword]}%" ,current_user)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|

  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message

  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    
  
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :users, "チャットメンバーを追加", class: 'chat-group-form__label', for:'user-search-field'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = f.text_field :users, id: 'user-search-field', class: 'chat-group-form__input', value: '', placeholder: '追加したいユーザー名を入力してください'
      #user-search-result
        

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :user_ids, "チャットメンバー", class: 'chat-group-form__label'

    .chat-group-form__field--right
      #chat-group-users
        - @group.users.each do |user|
          #chat-group-user-8.chat-group-user.clearfix.js-chat-member
            %input{name: 'group[user_ids][]', type: 'hidden', value: "#{ user.id }"}
            %p.chat-group-user__name
              = user.name
            %p.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
              - unless current_user.id == user.id
                削除

      #member_search_result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    %meta{content: "authenticity_token", name: "csrf-param"}/
    %meta{content: "OBD09dRVBvqnLkmry+UhjVFmoMlM12gQXDomVDWjfVL+w4dv1CvCCXXKriaTb52loRSxRqDlgHzIfkBEmJLhnw==", name: "csrf-token"}/
    %link{"data-turbolinks-track": "reload", href: "/assets/application-20597f7122b97f433c4487edf7d6a0cfc9e951e2a661b8b0c7320b95bbd38ccd.css", media: "all", rel: "stylesheet"}/
    %script{"data-turbolinks-track": "reload", src: "/assets/application-92a91cf5753a538c5407a46c726acab43576fb46358ffa8a7ee0ee0719aa2f51.js"}
  %body
    .flash-box
    .wrapper
      .chat-side
        .side-header
          .side-header__box
            %h3.header__name
              = current_user.name
            %ul.header__lists
              %li.list
                = link_to new_group_path do
                  = fa_icon 'pencil-square-o', class: 'icon'
              %li.list
                = link_to edit_user_path(current_user) do
                  = fa_icon 'cog', class: 'icon'
        .groups
          - current_user.groups.each do |group|
            .group
              -# - current_user.groups.each do |group|
              = link_to group_messages_path(group) do
                .group__name
                  = group.name
                .group__message
                  = group.show_last_message

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.message{"data-message-id": "#{message.id}"}
  .upper-message
    .upper-message__user-name
      = message.user.name
    .upper-message__date
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  .lower-message
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.flash-box
.wrapper
  .chat-side
    .side-header
      .side-header__box
        %h3.header__name
          = current_user.name
        %ul.header__lists
          %li.list
            = link_to new_group_path do
              = fa_icon 'pencil-square-o', class: 'icon'
          %li.list
            = link_to edit_user_path(current_user) do
              = fa_icon 'cog', class: 'icon'
    
    .groups
      -# - current_user.groups.each do |group|
      - current_user.groups.each do |group|
        = link_to group_messages_path(group) do
          .group
            -# - current_user.groups.each do |group|
            = link_to group_messages_path(group) do
              .group__name
                = group.name
              .group__message
                = group.show_last_message
  .chat-main
    .main-header
      .main-header__left-box


        %h2.main-header__left-box__current-group
          =@group.name
        %ul.main-header__left-box__member-list
          Member：
          %li.main-header__left-box__member-list__name
          - @group.group_users.each do |group_user|
            = group_user.user.name


      = link_to edit_group_path(@group) do
        .main-header__edit-btn{"data-turbolinks": "false"}
          Edit
    .messages
      = render @messages
    .form
      = form_for [@group, @message] do |f|
        .input-box
          = f.text_field :content, class: 'input-box__text', placeholder: 'type a message'
          %label.input-box__image{for: 'message_image'}
            = fa_icon 'picture-o', class: 'fa.fa-image'
            = f.file_field :image, class: 'input-box__image__file'
        = f.submit 'Send', class: 'submit-btn'

app/views/messages/kuroi.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpaceSample
    %meta{:content => "authenticity_token", :name => "csrf-param"}/
    %meta{:content => "OBD09dRVBvqnLkmry+UhjVFmoMlM12gQXDomVDWjfVL+w4dv1CvCCXXKriaTb52loRSxRqDlgHzIfkBEmJLhnw==", :name => "csrf-token"}/
    %link{"data-turbolinks-track" => "reload", :href => "/assets/application-20597f7122b97f433c4487edf7d6a0cfc9e951e2a661b8b0c7320b95bbd38ccd.css", :media => "all", :rel => "stylesheet"}/
    %script{"data-turbolinks-track" => "reload", :src => "/assets/application-92a91cf5753a538c5407a46c726acab43576fb46358ffa8a7ee0ee0719aa2f51.js"}
  %body
    .flash-box
    .wrapper
      .chat-side
        .side-header
          .side-header__box
            %p.side-header__box__user-name kuroki
            %ul.side-header__box__menu
              %li.side-header__box__menu__new-group
                %a{:href => "/groups/new"}
                  %i.fa.fa-edit
              %li.side-header__box__menu__edit-user
                %a{:href => "/users/1466/edit"}
                  %i.fa.fa-cog
        .groups
          %a{:href => "/groups/3205/messages"}
            .group
              %p.group__group-name krkgroup
              %p.group__latest-message test
          %a{:href => "/groups/3397/messages"}
            .group
              %p.group__group-name krkgroup
              %p.group__latest-message まだメッセージがありません
      .chat-main
        .main-header
          .main-header__left-box
            %h2.main-header__left-box__current-group{"data-group_id" => "3205"}
              krkgroup
            %ul.main-header__left-box__member-list
              Member：
              %li.main-header__left-box__member-list__member miwa
              %li.main-header__left-box__member-list__member kuroki
          %a{:href => "/groups/3205/edit"}
            .main-header__edit-btn Edit
        .messages
          .message{"data-message_id" => "8521"}
            .message__upper-info
              %p.message__upper-info__talker kuroki
              %p.message__upper-info__date 2019/08/12(Mon) 21:32:46
            %p.message__text test
          .message{"data-message_id" => "8522"}
            .message__upper-info
              %p.message__upper-info__talker kuroki
              %p.message__upper-info__date 2019/08/12(Mon) 21:33:06
            %p.message__text
          .message{"data-message_id" => "8884"}
            .message__upper-info
              %p.message__upper-info__talker kuroki
              %p.message__upper-info__date 2019/08/16(Fri) 15:38:46
            %p.message__text test
          .message{"data-message_id" => "8973"}
            .message__upper-info
              %p.message__upper-info__talker kuroki
              %p.message__upper-info__date 2019/08/17(Sat) 14:06:02
            %p.message__text test
        .form
          %form#new_message.new_message{"accept-charset" => "UTF-8", :action => "/groups/3205/messages", :enctype => "multipart/form-data", :method => "post"}
            %input{:name => "utf8", :type => "hidden", :value => "✓"}/
            %input{:name => "authenticity_token", :type => "hidden", :value => "qvdNaRq2i6uaB6gNaATkbckF1QgYrZ7Hlz81qC2TwMbwAnYaqF4Mhx7mW2fzKs6RHaqLqolH1DFtyuoH/F19hw=="}/
            .input-box
              %input#message_content.input-box__text{:name => "message[content]", :placeholder => "type a message", :type => "text"}/
              %label.input-box__image{:for => "message_image"}
                %i.fa.fa-image
                %input#message_image.input-box__image__file{:name => "message[image]", :type => "file"}/
            %input.submit-btn{"data-disable-with" => "Send", :name => "commit", :type => "submit", :value => "Send"}/

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/shared/_side_bar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__lists
      %li.list
        = link_to do
          = fa_icon 'pencil-square-o', class: 'icon'
      %li.list
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog', class: 'icon'
  .groups
    .group
      .group__name
        グループ名
      .group__message
        新着メッセージ
    .group
      .group__name
        グループ名
      .group__message
        新着メッセージ
    .group
      .group__name
        グループ名
      .group__message
        新着メッセージ